title:             Dulio技术角
email:             shenhd@mosrv.com
description:       记录技术日常
author:            Dulio
baseurl:           ""
url:               "http://dulio.github.io"

# Social Profiles
twitter_username:
github_username:   dulio
facebook_username:

# Build settings
markdown:          kramdown
paginate:          15
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Server Config
port: 9000
